services:
    node-app:
        build:
            context: .
            target: production
        container_name: node-app-prod
        ports:
            - '4001:4001'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            NODE_ENV: development
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        restart: unless-stopped
        env_file:
            - .env.production

    postgres:
        container_name: postgres-prod
        ports:
            - '5432:5432'
        volumes:
            # - ./create-postgres-role.sql:/docker-entrypoint-initdb.d/create-postgres-role.sql
            - progresDB:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        env_file:
            - .env.production


    redis:
        ports:
            - '6379:6379'
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        env_file:
            - .env.production
